name: .NET Core

on:
  push:
    branches: [ training-2-2/yklee ]
#  pull_request:
#    branches: [ dev ]
#  Upload 대상자 변경 테스트

env:
  GitHubPackageFeedUrl: https://nuget.pkg.github.com/GitHubDevOps-Team3/index.json
  LogicProjectPath: ${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic
  AZURE_WEBAPP_NAME: AzureSprintWebAppTestYKLEE
  VERSION: 1.0.0
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates a GITHUB\_TOKEN secret to use in your workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        source-url: ${{ env.GitHubPackageFeedUrl }}

#    - name: Package up Project
#      run: dotnet pack --configuration Release ${{env.LogicProjectPath}}

#     run: dotnet pack -o . -p:PackageVersion=${{ env.VERSION }}.${{ github.run_number }}
    - name: Package up Project
      run: dotnet pack -o . -p:PackageVersion=${{ env.VERSION }}.${{ github.run_number }}

    - name: Push package to GitHub registry
      run: dotnet nuget push ${{env.LogicProjectPath}}/**/*.nupkg --skip-duplicate

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests --no-restore --verbosity normal

    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: /home/runner/work/animal-adoption-portal/animal-adoption-portal/AnimalAdoption.Web.Portal/bin/Release/netcoreapp3.1/AnimalAdoption.Web.Portal.dll